# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngRPC.proto\"P\n\x0cGraphRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x18\n\x04type\x18\x02 \x01(\x0e\x32\n.GraphType\x12\x18\n\x04info\x18\x03 \x01(\x0b\x32\n.GraphInfo\"\x96\x01\n\tGraphInfo\x12\x1a\n\x08\x62\x61r_info\x18\x01 \x01(\x0b\x32\x08.BarInfo\x12\x1a\n\x08pie_info\x18\x02 \x01(\x0b\x32\x08.PieInfo\x12\x1e\n\ndonut_info\x18\x03 \x01(\x0b\x32\n.DonutInfo\x12\x31\n\x14network_diagram_info\x18\x04 \x01(\x0b\x32\x13.NetworkDiagramInfo\"q\n\x07\x42\x61rInfo\x12\x0e\n\x06labels\x18\x01 \x03(\t\x12\x0e\n\x06values\x18\x02 \x03(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0e\n\x06xlabel\x18\x04 \x01(\t\x12\x0e\n\x06ylabel\x18\x05 \x01(\t\x12\x17\n\x0fxticks_rotation\x18\x06 \x01(\x05\"8\n\x07PieInfo\x12\x0e\n\x06labels\x18\x01 \x03(\t\x12\x0e\n\x06values\x18\x02 \x03(\x05\x12\r\n\x05title\x18\x03 \x01(\t\"M\n\tDonutInfo\x12\x0e\n\x06labels\x18\x01 \x03(\t\x12\x0e\n\x06values\x18\x02 \x03(\x05\x12\x11\n\thole_size\x18\x03 \x01(\x02\x12\r\n\x05title\x18\x04 \x01(\t\"H\n\x12NetworkDiagramInfo\x12\r\n\x05nodes\x18\x01 \x03(\t\x12\x14\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x05.Edge\x12\r\n\x05title\x18\x03 \x01(\t\"&\n\x04\x45\x64ge\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\" \n\x10WordCloudRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\rImageResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c*=\n\tGraphType\x12\x07\n\x03\x42\x41R\x10\x00\x12\x07\n\x03PIE\x10\x01\x12\t\n\x05\x44ONUT\x10\x02\x12\x13\n\x0fNETWORK_DIAGRAM\x10\x03\x32y\n\x0fResumeProcessor\x12.\n\rGenerateGraph\x12\r.GraphRequest\x1a\x0e.ImageResponse\x12\x36\n\x11GenerateWordCloud\x12\x11.WordCloudRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRAPHTYPE']._serialized_start=686
  _globals['_GRAPHTYPE']._serialized_end=747
  _globals['_GRAPHREQUEST']._serialized_start=14
  _globals['_GRAPHREQUEST']._serialized_end=94
  _globals['_GRAPHINFO']._serialized_start=97
  _globals['_GRAPHINFO']._serialized_end=247
  _globals['_BARINFO']._serialized_start=249
  _globals['_BARINFO']._serialized_end=362
  _globals['_PIEINFO']._serialized_start=364
  _globals['_PIEINFO']._serialized_end=420
  _globals['_DONUTINFO']._serialized_start=422
  _globals['_DONUTINFO']._serialized_end=499
  _globals['_NETWORKDIAGRAMINFO']._serialized_start=501
  _globals['_NETWORKDIAGRAMINFO']._serialized_end=573
  _globals['_EDGE']._serialized_start=575
  _globals['_EDGE']._serialized_end=613
  _globals['_WORDCLOUDREQUEST']._serialized_start=615
  _globals['_WORDCLOUDREQUEST']._serialized_end=647
  _globals['_IMAGERESPONSE']._serialized_start=649
  _globals['_IMAGERESPONSE']._serialized_end=684
  _globals['_RESUMEPROCESSOR']._serialized_start=749
  _globals['_RESUMEPROCESSOR']._serialized_end=870
# @@protoc_insertion_point(module_scope)
